dist: trusty

language: scala
scala:
  - 2.11.12
  - 2.12.11

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
  - openjdk9
  - openjdk10

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
